### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by benjamincburns** [benjamincburns/websockproxy#13]
I originally licensed this under GPLv2, however my personal philosophy behind FOSS has changed a bit, and I'd prefer to update this to the more permissive MIT license.

**Comment by benjamincburns** [comment]
@copy as the only other person who's contributed code to this project to date, are you happy for me to change the license over to MIT?

**Comment by copy** [comment]
> @copy as the only other person who's contributed code to this project to date, are you happy for me to change the license over to MIT?

Yeah, changing the license to MIT is fine for me.
