### ISSUE TITLE
 The certificate for relay.widgetry.org expired on 12/07/2021.

### ISSUE THREAD

**Issue by edent** [benjamincburns/websockproxy#7]
Trying to access https://relay.widgetry.org/ & wss://relay.widgetry.org/ is failing due to:

> The certificate for relay.widgetry.org expired on 12/07/2021.
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Looks like you need to refresh Let's Encrypt.

**Comment by benjamincburns** [comment]
Poor little certbot, he lived for so, so long... I'll look into it - thanks!

**Comment by benjamincburns** [comment]
Apparently my certbot was old enough that it didn't have ACMEv2 support. A sudo apt upgrade -y && sudo certbot renew took care of it. Looks to be all good now.

![image](https://user-images.githubusercontent.com/803016/128023763-afe6025e-6d99-4451-a161-f77a59dc0cff.png)
